### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by GiridharRNair** [fregante/chrome-webstore-upload-keys#1]
I am getting an error after opening the browser and completing the process.

```
┌  Follow the steps at this URL to generate the API keys, then enter them below to generate the refresh token.
   https://github.com/fregante/chrome-webstore-upload-keys
│
◇  Client ID:
│  <My Client ID>
│
◇  Client secret:
│  <My Client Secret>
│
◇  Open the authentication page in the default browser?
│  Yes
│
◇  Complete the process in the browser. Follow its steps and warnings (this is your own personal app)
│
◇  Approval code received from Google
│
▲  Something went wrong
file:///Users/myname/.npm/_npx/2fa460884147c18c/node_modules/chrome-webstore-upload-keys/dist/index.js:301
        const request = await fetch('https://accounts.google.com/o/oauth2/token', {
                        ^

ReferenceError: fetch is not defined
    at getRefreshToken (file:///Users/myname/.npm/_npx/2fa460884147c18c/node_modules/chrome-webstore-upload-keys/dist/index.js:301:18)
    at Object.task (file:///Users/myname/.npm/_npx/2fa460884147c18c/node_modules/chrome-webstore-upload-keys/dist/index.js:388:25)
    at tasks (file:///Users/myname/.npm/_npx/2fa460884147c18c/node_modules/chrome-webstore-upload-keys/dist/index.js:269:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/myname/.npm/_npx/2fa460884147c18c/node_modules/chrome-webstore-upload-keys/dist/index.js:365:1
```

**Comment by fregante** [comment]
v3 requires Node 18+

**Comment by GiridharRNair** [comment]
Thanks, careless mistake

**Comment by fregante** [comment]
I'll add an early message so you don't get stopped after entering everything
